name: drivo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  get: ^4.6.1
  get_storage: ^2.0.3
  google_fonts: ^2.2.0
  jwt_decoder: ^2.0.1
  logger: ^1.1.0
  shared_preferences: ^2.0.11
  flutter_osm_plugin: ^0.28.0+1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/splashScreen/
    - assets/icons/
    - assets/dummyData/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
