name: drivo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  device_info_plus: ^3.2.1
  dio: ^4.0.4
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.2.0
  flutter_osm_plugin: ^0.28.0+1
  fluttertoast: ^8.0.8
  get: ^4.6.1
  get_storage: ^2.0.3
  google_fonts: ^2.2.0
  google_maps_flutter: ^2.1.1
  http: ^0.13.4
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  location: ^4.3.0
  logger: ^1.1.0
  shared_preferences: ^2.0.11

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/splashScreen/
    - assets/icons/
  fonts:
    - family: GothamPro
      fonts:
        - asset: assets/fonts/Gotham/GothamPro-Medium.ttf
        - asset: assets/fonts/Gotham/GothamPro-Light.ttf
        - asset: assets/fonts/Gotham/GothamPro-Black.ttf
        - asset: assets/fonts/Gotham/GothamPro-BlackItalic.ttf
        - asset: assets/fonts/Gotham/GothamPro-Italic.ttf
        - asset: assets/fonts/Gotham/GothamPro.ttf
          weight: 900
    - family: russian
      fonts:
        - asset: assets/fonts/russian/ui_icons.ttf
        
